"""empty message

Revision ID: a5cffa318ac2
Revises: 
Create Date: 2023-10-31 13:53:01.946815

"""
from alembic import op
import sqlalchemy as sa

revision = 'a5cffa318ac2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.create_table('user',
    sa.Column('id', sa.Integer()),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('firstname', sa.String(length=100)), 
    sa.Column('lastname', sa.String(length=100)), 
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.Index('ix_user_username', 'username'),
    sa.UniqueConstraint('email')
    )
    op.create_table('follower',
    sa.Column('user_from_id', sa.Integer(), sa.ForeignKey('user.id'), primary_key=True),
    sa.Column('user_to_id', sa.Integer(), sa.ForeignKey('user.id'), primary_key=True),
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), primary_key=True),
    sa.Column('comment_text', sa.String(length=250), nullable=False),
    sa.Column('author_id', sa.Integer(), sa.ForeignKey('user.id'), nullable=False),
    sa.Column('post_id', sa.Integer(), sa.ForeignKey('user.id'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), primary_key=True),
    sa.Column('user_id', sa.Integer(), sa.ForeignKey('post.id'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    )
    op.create_table('media',
    sa.Column('id', sa.Integer(), primary_key=True),
    sa.Column('type', sa.Enum('image', 'video', name='media_type'), nullable=False),
    sa.Column('url', sa.String(length=250), nullable=False),
    sa.Column('post_id', sa.Integer(), sa.ForeignKey('post.id'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('follower')
    op.drop_table('comment')
    op.drop_table('post')
    op.drop_table('media')
    # ### end Alembic commands ###
